# -*- coding: utf-8 -*-
"""practical 8(DAA) bfs & dfs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7ZpJIyeh0ve-5qQ4JKVM-aoyiMAPQlJ
"""

from collections import deque

graph = {
    'A': ['B', 'C'],
    'B': ['A', 'D', 'E'],
    'C': ['A', 'F'],
    'D': ['B'],
    'E': ['B', 'F'],
    'F': ['C', 'E']
}

def bfs(start):
    visited = set()
    queue = deque([start])
    result = []

    while queue:
        node = queue.popleft()

        if node not in visited:
            visited.add(node)
            result.append(node)

            for neighbor in graph[node]:
                if neighbor not in visited:
                    queue.append(neighbor)

    return result


def dfs(start):
    visited = set()
    result = []

    def dfs_recursive(node):
        visited.add(node)
        result.append(node)

        for neighbor in graph[node]:
            if neighbor not in visited:
                dfs_recursive(neighbor)

    dfs_recursive(start)
    return result


print("Graph:")
for node in graph:
    print(node, "->", graph[node])

print("\nBFS Traversal:", bfs('A'))
print("DFS Traversal:", dfs('A'))