# -*- coding: utf-8 -*-
"""practical 9(DAA) prim's algo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQt_DnrqlX3-PtRt-sdNR6oRDUeHNN3e
"""

def fun(graph, start):
    nodes = list(graph.keys())

    key = {node: 999999 for node in nodes}
    parent = {node: None for node in nodes}
    visited = {node: False for node in nodes}

    key[start] = 0
    path = []

    for _ in range(len(nodes)):
        minimum = 999999
        u = None

        for node in nodes:
            if not visited[node] and key[node] < minimum:
                minimum = key[node]
                u = node

        visited[u] = True
        path.append(u)

        for v in nodes:
            if graph[u][v] != 0 and not visited[v]:
                if graph[u][v] < key[v]:
                    key[v] = graph[u][v]
                    parent[v] = u

    print("Edges in Minimum Spanning Tree:")

    total = 0

    for node in nodes:
        if parent[node] is not None:
            print(parent[node], "-", node, ":", graph[node][parent[node]])
            total += graph[node][parent[node]]

    print("\nPath:", " -> ".join(path))
    print("Minimum Cost:", total)


graph = {
    'A': {'A': 0, 'B': 2, 'C': 0, 'D': 6, 'E': 0},
    'B': {'A': 2, 'B': 0, 'C': 3, 'D': 8, 'E': 5},
    'C': {'A': 0, 'B': 3, 'C': 0, 'D': 0, 'E': 7},
    'D': {'A': 6, 'B': 8, 'C': 0, 'D': 0, 'E': 9},
    'E': {'A': 0, 'B': 5, 'C': 7, 'D': 9, 'E': 0}
}

fun(graph, 'A')